// Define sets of names
const maleNames = ["Addam", "Aden", "Albert", "Alder", "Aldwyn", "Aleric", "Alesander", "Alester", "Alfred", "Allard", "Alvyn", "Alyn", "Amory", "Arden", "Aren", "Aric", "Arley", "Arnold", "Arthur", "Awen", "Baldwyn", "Barenn", "Benjamin", "Bertram", "Braden", "Brandon", "Bryan", "Byron", "Caden", "Calder", "Calvyn", "Carbrey", "Casemyr", "Cassius", "Castor", "Cayn", "Cedrick", "Clyde", "Clyve", "Colyn", "Corwin", "Cyrus", "Damon", "Daryl", "Davys", "Daven", "Denys", "Deryck", "Desmond", "Doren", "Dorian", "Drakon", "Dunn", "Duncan", "Dustyn", "Eamon", "Edd", "Edgar", "Edmund", "Edric", "Edryck", "Edwyn", "Edwyrd", "Eldric", "Eldyn", "Elias", "Ellys", "Elwyn", "Erek", "Erwyn", "Falk", "Farrel", "Feron", "Feyric", "Finlay", "Finn", "Flynn", "Forrest", "Frederick", "Fyran", "Gareth", "Garey", "Garrick", "Gawen", "Gerold", "Glenn", "Gregor", "Gryffard", "Gyles", "Gyll", "Harald", "Harlan", "Harmon", "Harren", "Henrick", "Howard", "Ian", "Irwyn", "Jakob", "Jarod", "Jasper", "Jayce", "Jaymes", "Jeffrey", "Jon", "Kaden", "Kalen", "Kaspar", "Kenryck", "Kevan", "Leander", "Lennard", "Leon", "Lester", "Lewyn", "Lloyd", "Lorian", "Lucas", "Lucian", "Lyander", "Lyon", "Lyonard", "Lyonel", "Lyor", "Lyren", "Lysander", "Mark", "Markus", "Marlen", "Martyn", "Marvyn", "Meldrick", "Melvyn", "Merlyn", "Merrick", "Mervyn", "Mordred", "Morgen", "Morwen", "Myles", "Mylton", "Neryn", "Nolan", "Nyall", "Oberon", "Ogden", "Olyver", "Oryn", "Osbert", "Osgood", "Osmond", "Osric", "Oswald", "Oswyn", "Owyn", "Patrek", "Perryn", "Prestyn", "Quentyn", "Randall", "Raymund", "Reed", "Reynard", "Rhygar", "Rhys", "Robert", "Robyn", "Roderick", "Rolf", "Rollynd", "Roserick", "Roswell", "Rowan", "Royce", "Ryan", "Rubyn", "Rykard", "Sabyn", "Sammen", "Sander", "Selman", "Sewyrd", "Shayne", "Sorren", "Stafford", "Stannen", "Stefan", "Swayne", "Sybald", "Syd", "Sylas", "Sylvester", "Symon", "Terrel", "Thayne", "Thedan", "Theon", "Theryn", "Tom", "Tomas", "Tobias", "Tobin", "Todd", "Tolbert", "Torren", "Travys", "Trey", "Trystan", "Tyberus", "Tyan", "Tyras", "Tyron", "Tyven", "Ulfrick", "Ulick", "Ullar", "Ulric", "Ulyn", "Uwen", "Valkar", "Varrick", "Varron", "Vellyn", "Vergyl", "Vernon", "Veryn", "Vesryn", "Wallys", "Waltyr", "Ward", "Warren", "Warwyck", "Wayne", "Wendel", "Westley", "Wright", "Wulfrick", "Wyatt", "Wulf", "Wyll", "Wyllam", "Wyllis", "Wylmer", "Wylson", "Wymond", "Wynslow", "Wynn", "Wynston", "Wyrman", "Wystan", "Ywain", "Zorren"];
const femaleNames = {
  Oldblood: ["Ada", "Agatha", "Agnys", "Alanna", "Alanys", "Alayna", "Alys", "Alysandra", "Alyse", "Alyssa", "Anna", "Annora", "Arden", "Arwyn", "Astryd", "Avelyn", "Barenna", "Berta", "Bethany", "Branna", "Brena", "Bridget", "Caralyn", "Carmella", "Carmyne", "Cassandra", "Catelyn", "Cathryn", "Catryn", "Cerenna", "Cora", "Corynn", "Damya", "Daphne", "Dayanna", "Dayna", "Denyse", "Desdemona", "Donella", "Dyanna", "Dyna", "Edanna", "Edda", "Edwyna", "Edyth", "Elayne", "Elinor", "Elisabeth", "Ellyn", "Elyane", "Elysa", "Elyse", "Emelynn", "Enys", "Erycka", "Erynn", "Fawna", "Felyse", "Fredda", "Freyda", "Fyona", "Gawena", "Gayle", "Genna", "Geroldyne", "Glenna", "Greta", "Gwen", "Gwenyth", "Gwyn", "Gwyndolyn", "Gwynna", "Hanna", "Hylda", "Ida", "Innys", "Isolde", "Janna", "Janys", "Jenefer", "Jeyna", "Jeyne", "Joanna", "Jonna", "Kendra", "Kenna", "Lenora", "Leona", "Lisbeth", "Lorayne", "Lya", "Lyanna", "Lyanora", "Lyda", "Lylla", "Lynda", "Lynna", "Lyra", "Lysa", "Lysandra", "Lyssa", "Margaret", "Margery", "Marla", "Marra", "Maura", "Mavys", "Mayla", "Mayra", "Mayve", "Megyn", "Meredyth", "Mildryth", "Morgana", "Morla", "Morna", "Morwenna", "Morwyn", "Mya", "Mylla", "Myra", "Myriah", "Myrna", "Nadya", "Nella", "Netta", "Nora", "Nyanna", "Nyara", "Orla", "Owena", "Petra", "Ravenna", "Raymona", "Rayne", "Reanna", "Rhea", "Roberta", "Rosalyn", "Rosamund", "Roswenna", "Roswyn", "Rowenna", "Rya", "Ryana", "Rykarda", "Sabryna", "Sanna", "Sara", "Saranna", "Seanna", "Shanna", "Stefany", "Susenna", "Sybella", "Sygrid", "Sylla", "Tabatha", "Tamsyn", "Thalyra", "Thea", "Theda", "Theona", "Tomasyn", "Tyana", "Tylda", "Ulla", "Ulrica", "Valery", "Vanessa", "Vena", "Vessa", "Wrynne", "Wylfreda", "Wylla", "Wylma", "Wynna", "Yara", "Ysolde"],
  Blessed: ["Alanna", "Alanys", "Alayna", "Alessa", "Alys", "Alysandra", "Alysanne", "Alyse", "Alyssa", "Anna", "Annelyse", "Annora", "Anyse", "Arella", "Aryana", "Ashyra", "Astra", "Barenna", "Beatrys", "Belynda", "Bessalyn", "Beth", "Bethany", "Branna", "Brena", "Bryanna", "Bryanne", "Bryony", "Bryssa", "Calanthe", "Calla", "Camylla", "Carmella", "Cassia", "Cerenna", "Ceryse", "Chella", "Chryssa", "Claryse", "Claryssa", "Clea", "Cora", "Coryssa", "Cyara", "Cyrenna", "Damya", "Daphne", "Dayanna", "Dayna", "Delora", "Delphyne", "Donella", "Dora", "Dyanna", "Elanna", "Elara", "Elayne", "Elessa", "Ellyn", "Elowyn", "Eloyse", "Elyane", "Elysa", "Elyse", "Emelynn", "Eowyn", "Essa", "Evelynne", "Fawna", "Faye", "Felyse", "Feyra", "Florynne", "Fyona", "Gawena", "Gayle", "Genna", "Gillian", "Glenna", "Gwen", "Gwenyth", "Gwyn", "Gwyndolyn", "Gwynna", "Gyna", "Gyselle", "Hanna", "Helena", "Heleyna", "Heleyne", "Illyra", "Ilyssa", "Isabel", "Isadora", "Janey", "Janna", "Janys", "Jasmyne", "Jeanna", "Jenefer", "Jenessa", "Jessalyn", "Jessamyne", "Jeyna", "Jeyne", "Joanna", "Jocella", "Jocelyn", "Jonna", "Kalla", "Kalysta", "Kenna", "Lacey", "Lanessa", "Laney", "Laura", "Lavena", "Lenora", "Leona", "Lessa", "Lilly", "Lillyanne", "Lorayne", "Lya", "Lyanna", "Lyanora", "Lycia", "Lyda", "Lylla", "Lynda", "Lynesse", "Lynette", "Lynna", "Lyra", "Lysa", "Lysanne", "Lyssa", "Madalyn", "Maralyn", "Marcelyne", "Marelle", "Maryse", "Maryssa", "Maybell", "Mayla", "Maylise", "Mayra", "Melantha", "Melynda", "Melyora", "Melyssa", "Mya", "Mylla", "Nella", "Neryssa", "Nessa", "Netta", "Nora", "Nyanna", "Nyara", "Olyve", "Olyvia", "Orla", "Oryanna", "Oryanne", "Ossia", "Owena", "Pearle", "Pippa", "Reanna", "Robynne", "Rosalyn", "Rosamund", "Rosanna", "Rosemary", "Roswenna", "Roswyn", "Rowenna", "Ruby", "Sabella", "Sanna", "Sara", "Sarafine", "Saranna", "Sarella", "Selena", "Selessa", "Selyne", "Shanna", "Sharyse", "Sofya", "Sorelle", "Susenna", "Sybella", "Syena", "Sylenna", "Sylira", "Sylla", "Sylva", "Sylveyne", "Syra", "Syvanna", "Tabatha", "Telyssa", "Terysa", "Tessa", "Thalyra", "Theylse", "Tryssa", "Twyla", "Tyana", "Ulyra", "Valery", "Valestra", "Velessa", "Vella", "Vena", "Verenna", "Vessa", "Vyra", "Vyrella", "Yara", "Ysara", "Zenna"],
  Wyrmbound: ["Ada", "Agatha", "Agnys", "Alanna", "Alanys", "Alayna", "Alessa", "Alys", "Alysandra", "Annora", "Ara", "Arden", "Arella", "Arwyn", "Aryana", "Ashyra", "Astra", "Barenna", "Beatrys", "Belynda", "Bessalyn", "Beth", "Bethany", "Branna", "Brena", "Bridget", "Bryanna", "Bryanne", "Bryony", "Bryssa", "Caralyn", "Carmella", "Carmyne", "Cassandra", "Cassia", "Catelyn", "Cathryn", "Catryn", "Cerenna", "Ceryse", "Chella", "Chryssa", "Claryse", "Claryssa", "Clea", "Cora", "Corynn", "Corynna", "Coryssa", "Cyara", "Cyndra", "Cyrenna", "Damya", "Daphne", "Dayanna", "Dayna", "Delora", "Delphyne", "Denyse", "Desdemona", "Donella", "Dora", "Drakessa", "Drusylla", "Dyanna", "Dyna", "Elanna", "Elara", "Elayne", "Elessa", "Fawna", "Faye", "Felyse", "Feyra", "Florynne", "Fredda", "Freyda", "Fyona", "Gawena", "Gayle", "Genna", "Gillian", "Glenna", "Greta", "Gyselle", "Hanna", "Helena", "Heleyna", "Heleyne", "Hylda", "Ida", "Illyra", "Ilyssa", "Innys", "Isabel", "Isadora", "Isolde", "Jenefer", "Jeyna", "Jeyne", "Kalla", "Kalysta", "Kaylyn", "Kendra", "Kenna", "Lacey", "Lanessa", "Laney", "Laura", "Lavena", "Lenora", "Leona", "Lessa", "Lilly", "Lillyanne", "Lorayne", "Lya", "Lyanna", "Lyanora", "Lycia", "Lyda", "Lylla", "Lynda", "Lynesse", "Lynette", "Lynna", "Lyra", "Lysa", "Lysandra", "Lysanne", "Lyssa", "Madalyn", "Maralyn", "Marcelyne", "Marelle", "Margaret", "Margery", "Marys", "Maryse", "Maryssa", "Maura", "Mavys", "Mayla", "Maylise", "Mayra", "Mayve", "Megyn", "Melantha", "Melynda", "Melyora", "Melyssa", "Meredyth", "Mildryth", "Morgana", "Morla", "Morna", "Morwenna", "Morwyn", "Mya", "Mylla", "Myra", "Myriah", "Myrna", "Nadya", "Nella", "Neryssa", "Nessa", "Netta", "Nora", "Nyanna", "Nyara", "Orla", "Oryanna", "Oryanne", "Ossia", "Owena", "Petra", "Ravenna", "Raymona", "Rayne", "Reanna", "Rhea", "Robynne", "Rosalyn", "Rosamund", "Rosanna", "Rosemary", "Roswenna", "Roswyn", "Rowenna", "Sabella", "Sabryna", "Sabyna", "Sanna", "Sara", "Sarafine", "Saranna", "Sarella", "Selena", "Selessa", "Selyne", "Shanna", "Sharyse", "Sofya", "Sorelle", "Susenna", "Sybella", "Syena", "Sylenna", "Sylira", "Sylla", "Sylva", "Sylveyne", "Syra", "Syvanna", "Tabatha", "Telyssa", "Terysa", "Tessa", "Thalyra", "Theylse", "Tryssa", "Twyla", "Tyana", "Ulyra", "Valery", "Valestra", "Velessa", "Vella", "Vena", "Verenna", "Veryna", "Vespera", "Vessa", "Vyra", "Vyrella", "Yara", "Ysara", "Zenna"],
};
const lastNames = {
  Erdwing: ["Thalmorren", "Bytide", "Anchor", "Gullwing", "Drift", "Fisher", "Burgess", "Dunsley", "Harroway", "Loxe", "Bramwell", "Goldyng", "Pearle", "Glimmercrest", "Porter", "Reefe", "Brightharbor", "Westmore", "Westerly", "Wyrmwind", "Sand", "Hawke", "Cliffrock", "Greymist", "Wader", "Salt", "Marlowe", "Ashcombe", "Hargrave", "Wycliffe", "Fairhaven", "Colton", "Bauble", "Highwater", "Wyrmport", "Dawne", "Crabber", "Petrel", "Darkwater", "Tidecall", "Coral", "Windrake"],
  Dragonfell: ["Duske", "Wyld", "Wulf", "Hare", "Holloway", "Ashwick", "Kindling", "Hearth", "Firelight", "Ardlain", "Corvane", "Sylverbark", "Blackthorne", "Crayden", "Kellen", "Drelwyn", "Duskenbridge-Duske", "Grey", "Fell", "Caldreth", "Stane", "Harwood", "Hart", "Fallow", "Wyrmwood", "Cedar", "Briarwood", "Stagg", "Pine", "Oakes", "Pell", "Fenwell", "Greymead", "Callanwright", "Vecke", "Grymme"],
  Dragonsblood: ["Bloodwyne", "Rosehip", "Ferrowine", "Grapeleaf", "Blushvine", "Cress", "Veralle", "Redwyne", "Oxley", "Grainger", "Stonewell", "Hart", "Mutton", "Meadows", "Vintmere-Bloodwyne", "Barrel", "Roselane", "Cask", "Berryburr", "Vintwell", "Trellis", "Redfield", "Dunsworth", "Garland", "Poppyfield", "Lavender", "Marigold", "Foxglove", "Rosewood", "Appleton", "Crabapple", "Orchard", "Pippin", "Harveston", "Cyder", "Whitevine-Bloodwyne", "Summerbottle", "Sunfield", "Honeywyne", "Brightwater", "Silverbrook", "Fair", "Goldswell", "Blake", "Swan", "Dove", "Lark", "Kestrel"],
  Wyrmspine: ["Clyfford", "Stormrest-Clyfford", "Hewn", "Veyric", "Shale", "Highquarry", "Veyne", "Stonewake", "Stormsong", "Payne", "Gravell", "Cairn", "Skelwyn", "Keffard", "Oldknoll", "Dustey", "Foothold", "Holm", "Wyvernrest", "Wyrmforge", "Ironhart", "Blackslag", "Anvilmight", "Emberbright"],
  Bloodmire: ["Drevant", "Weir", "Gloame", "Hallow", "Mourne", "Redclay", "Drakefang", "Wisp", "Bogwarden", "Graven", "Mirelight", "Fenmark", "Morgrave", "Wyrdwell", "Barrowmere", "Feld", "Crypt", "Morwyn", "Vyper", "Gloomlily", "Emberfen", "Vrydan", "Ashe"],
};

function generateNames() {
  const firstNameGender = document.getElementById("first-name-gender").value;
  const culture = document.getElementById("culture").value;
  const region = document.getElementById("region").value;

  const firstNames = firstNameGender === "Mixed"
    ? [...maleNames, ...femaleNames[culture]]
    : firstNameGender === "Male"
    ? maleNames
    : femaleNames[culture];

  const lastNameSets = region === "All"
    ? Object.values(lastNames).flat()
    : lastNames[region];

  const namesList = document.getElementById("names-list");
  namesList.innerHTML = ""; // Clear previous results

  // Generate 10 sets of names
  for (let i = 0; i < 10; i++) {
    const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
    const lastName = lastNameSets[Math.floor(Math.random() * lastNameSets.length)];
    const fullName = `${firstName} ${lastName}`;
    const listItem = document.createElement("li");
    listItem.textContent = fullName;
    namesList.appendChild(listItem);
  }
}
